{
 "title": "PaskPool Cluster",
 "description": "PaskPool Cluster monitor dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Stats - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Producer Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int" }
   ]
  },
  {
   "title": "Producer Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int"
    }
   ]
  },
  {
   "title": "Next Epoch begin's in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "432000 - cardano_node_metrics_slotInEpoch_int"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int / cardano_node_metrics_Forge_node_is_leader_int * 100",
     "legendFormat": "SKY_Core"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Backup" },
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Relay1" },
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Relay2" },
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Relay3" },
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Producer" }
   ]
  },
  {
   "title": "KES Period",
   "type": "stat",
   "description": "\"slotsPerKESPeriod\": 129600\n\"maxKESEvolutions\": 62",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateStartKESPeriod_int",
     "legendFormat": "Started"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expire"
    }
   ]
  },
  {
   "title": "OPCert. expire in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (cardano_node_metrics_operationalCertificateExpiryKESPeriod_int * 129600) - cardano_node_metrics_slotNum_int"
    }
   ]
  },
  {
   "title": "Decentralization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_epoch_int - 207) * 2"
    }
   ]
  },
  {
   "title": "Nodes Slot Height Sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "Backup (Backup)"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "Producer"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s]))",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "Backup"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "Producer"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "Density"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Paskpool" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int"
    }
   ]
  },
  {
   "title": "Free Ram",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"}\n"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"})*100)",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60",
     "legendFormat": "Block sync"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Relay1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "cardano_node_metrics_epoch_int" }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_connectedPeers_int"
      }
     ]
    },
    {
     "title": "Chain Density",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real * 100",
       "legendFormat": "Density"
      }
     ]
    },
    {
     "title": "Node Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Paskpool" }
     ]
    },
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_thermal_zone_temp" }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds)"
      }
     ]
    },
    {
     "title": "Slot",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotInEpoch_int"
      }
     ]
    },
    {
     "title": "Free Ram",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemAvailable_bytes" }
     ]
    },
    {
     "title": "Free Disk Space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"}\n"
      }
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_blockNum_int",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "System Health",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "CPU Load"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
       "legendFormat": "SWAP Utilization"
      },
      {
       "expr": "100 - ((node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"})*100)",
       "legendFormat": "Disk Utilization"
      }
     ]
    },
    {
     "title": "Slot Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotNum_int",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block sync speed (blocks / min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60",
       "legendFormat": "Block sync"
      }
     ]
    },
    {
     "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
     "type": "graph",
     "description": "/",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
       "legendFormat": "1h Cluster Data Received, bytes"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
       "legendFormat": "1h Cluster Data Transmitted, bytes"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "Load 1m" },
      { "expr": "node_load5", "legendFormat": "Load 5m" },
      { "expr": "node_load15", "legendFormat": "Load 15m" }
     ]
    },
    {
     "title": "Mempool Transactions",
     "type": "graph",
     "description": "current",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int",
       "legendFormat": "Transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "cardano_node_metrics_epoch_int" }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_connectedPeers_int"
      }
     ]
    },
    {
     "title": "Chain Density",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real * 100",
       "legendFormat": "Density"
      }
     ]
    },
    {
     "title": "Node Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Paskpool" }
     ]
    },
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_thermal_zone_temp" }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds)"
      }
     ]
    },
    {
     "title": "Slot",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotInEpoch_int"
      }
     ]
    },
    {
     "title": "Free Ram",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemAvailable_bytes" }
     ]
    },
    {
     "title": "Free Disk Space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"}\n"
      }
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_blockNum_int",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "System Health",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "CPU Load"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
       "legendFormat": "SWAP Utilization"
      },
      {
       "expr": "100 - ((node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"})*100)",
       "legendFormat": "Disk Utilization"
      }
     ]
    },
    {
     "title": "Slot Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotNum_int",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block sync speed (blocks / min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60",
       "legendFormat": "Block sync"
      }
     ]
    },
    {
     "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
     "type": "graph",
     "description": "/",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
       "legendFormat": "1h Cluster Data Received, bytes"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
       "legendFormat": "1h Cluster Data Transmitted, bytes"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "Load 1m" },
      { "expr": "node_load5", "legendFormat": "Load 5m" },
      { "expr": "node_load15", "legendFormat": "Load 15m" }
     ]
    },
    {
     "title": "Mempool Transactions",
     "type": "graph",
     "description": "current",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int",
       "legendFormat": "Transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "cardano_node_metrics_epoch_int" }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_connectedPeers_int"
      }
     ]
    },
    {
     "title": "Chain Density",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real * 100",
       "legendFormat": "Density"
      }
     ]
    },
    {
     "title": "Node Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Paskpool" }
     ]
    },
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_thermal_zone_temp" }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds)"
      }
     ]
    },
    {
     "title": "Slot",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotInEpoch_int"
      }
     ]
    },
    {
     "title": "Free Ram",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemAvailable_bytes" }
     ]
    },
    {
     "title": "Free Disk Space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"}\n"
      }
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_blockNum_int",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "System Health",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "CPU Load"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
       "legendFormat": "SWAP Utilization"
      },
      {
       "expr": "100 - ((node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"})*100)",
       "legendFormat": "Disk Utilization"
      }
     ]
    },
    {
     "title": "Slot Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotNum_int",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block sync speed (blocks / min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60",
       "legendFormat": "Block sync"
      }
     ]
    },
    {
     "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
     "type": "graph",
     "description": "/",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
       "legendFormat": "1h Cluster Data Received, bytes"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
       "legendFormat": "1h Cluster Data Transmitted, bytes"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 83 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "Load 1m" },
      { "expr": "node_load5", "legendFormat": "Load 5m" },
      { "expr": "node_load15", "legendFormat": "Load 15m" }
     ]
    },
    {
     "title": "Mempool Transactions",
     "type": "graph",
     "description": "current",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int",
       "legendFormat": "Transactions"
      }
     ]
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "Density"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / 3600000", "legendFormat": "Paskpool" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int"
    }
   ]
  },
  {
   "title": "Free Ram",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"}\n"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"127.0.0.1:9100\", job=\"host\", mountpoint=\"/etc/hostname\"})*100)",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60",
     "legendFormat": "Block sync"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "Transactions"
    }
   ]
  }
 ]
}